server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
mybatis:
  type-handlers-package: com.cskaoyan.mall.handler
#  # 启用shutdown
#management:
#  endpoint:
#    shutdown:
#      enabled: true
## 公开所有的端点
#
#endpoints:
#  web:
#    exposure:
#      include: *
