server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enterprise
    username: root
    password: 123456
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
mybatis:
  type-handlers-package: project2.project_mall.handler
